version: '3.8'

services:
  fastapi:
    build:
      context: fastapi
      dockerfile: Dockerfile
    networks: 
      - app-network
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 8008:8000
    depends_on:
      ollama:
        condition: service_healthy

  ollama:
    # Use smaller model for faster startup
    image: ollama/ollama:latest
    container_name: ollama-llm-dev
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_MODELS=llama2:7b-q4_0  # Quantized model
    volumes:
      - ./ollama_models_dev:/root/.ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
          memory: 6G  # Reduced for development
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    networks: 
      - app-network

  frontend:
    build:
      context: streamlit
      dockerfile: Dockerfile
    networks: 
      - app-network
    ports:
      - 8501:8501
    env_file:
      - .env
    depends_on:
      - fastapi
  ollama-setup:
    image: ollama/ollama:latest
    depends_on:
      - ollama
    volumes:
      - ./ollama_models_dev:/root/.ollama
    command: >
      sh -c "
        sleep 30 &&
        ollama pull llama2:7b &&
        echo 'Model ready!'
      "
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

