version: '3.8'

services:
  fastapi:
    build:
      context: fastapi
      dockerfile: Dockerfile
    networks: 
      AIservice: 
        aliases: 
          - backend.docker
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 8008:8000

  frontend:
    build:
      context: streamlit
      dockerfile: Dockerfile
    networks: 
      AIservice: 
        aliases: 
          - frontend.docker
    ports:
      - 8501:8501
    env_file:
      - .env
    depends_on:
      - fastapi

networks:
  AIservice:
    external: true

