version: '3.8'

services:
  fastapi:
    build:
      context: fastapi
      dockerfile: Dockerfile
    networks: 
      AIservice: 
        aliases: 
          - backend.docker
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 8008:8000

  frontend:
    build:
      context: streamlit
      dockerfile: Dockerfile
    networks: 
      AIservice: 
        aliases: 
          - frontend.docker
    ports:
      - 8501:8501
    env_file:
      - .env
    depends_on:
      - fastapi

  web:
    image: nginx:alpine
    networks: 
      AIservice: 
        aliases: 
          - web.docker
    ports:
      - 8080:80
    volumes:
      - ./privacy-policy.html:/usr/share/nginx/html/privacy-policy.html:ro
      - ./nginx-static.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  AIservice:
    external: true

