version: '3.8'

services:
  fastapi:
    build:
      context: fastapi
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 8008:8000

  frontend:
    build:
      context: streamlit
      dockerfile: Dockerfile
    ports:
      - 8501:8501
    env_file:
      - .env
    depends_on:
      - fastapi

  web:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./privacy-policy.html:/usr/share/nginx/html/privacy-policy.html:ro
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
