version: '3.8'

services:
  fastapi:
    build:
      context: fastapi
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app

  react-frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    depends_on:
      - fastapi

  web:
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./privacy-policy.html:/var/www/html/privacy-policy.html:ro
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - fastapi
      - react-frontend
