version: '3.8'

services:
  fastapi:
    build:
      context: fastapi
      dockerfile: Dockerfile
    # networks: 
    #   AIservice: 
    #     aliases: 
    #       - backend.docker
    env_file:
      - .env
    volumes:
      - .:/app
    # expose:
    #   - 8008

  streamlit:
    build:
      context: streamlit
      dockerfile: Dockerfile
    # networks: 
    #   AIservice: 
    #     aliases: 
    #       - frontend.docker
    container_name: streamlit
    restart: always
    env_file:
      - .env
    # ports:
    #   - 8501:8501
    depends_on:
      - fastapi

  reverse:
    container_name: reverse
    hostname: reverse
    restart: always
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - streamlit
      - fastapi

# networks:
#   AIservice:
#     external: true

